name: BIT Auto Leave
on:
  workflow_dispatch:
  schedule:
 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-t

jobs:
  Leave:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TELEPHONE: ${{ secrets.TELEPHONE }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/YoungKlaus/BIT_Auto_Leave.git
        cp -r BIT_Auto_Leave/* .
        pip3 install -r requirements.txt
        python3 BIT_leave.py
